config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :exhibits do
    collection do
      get 'creation'
    end
  end
  resources :gabinete_objects do
    collection do
      get 'creation'
    end
    member do
      get :acbeu
    end
  end
  resources :histories do
    collection do
      get 'creation'
    end
  end
  resources :photos do
    collection do
      get 'creation'
    end
  end

  resources :comments do
    collection do
      get 'creation'
    end
  end

  get 'static_pages/home'
  get 'static_pages/monos'
  get 'static_pages/show_exp'
  get 'static_pages/acbeu'
  match "/depoimentos" => "static_pages#acbeu", via: :get

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  is_impressionable
  has_many :gabinete_objects, :dependent => :destroy
  has_many :photos, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_action :set_exhibit, only: [:show, :edit, :update, :destroy, :index_edition]

  # GET /exhibits
  # GET /exhibits.json
  def index
    @exhibits = Exhibit.all
  end
  
  def creation
    @exhibits = Exhibit.all
  end

  # GET /exhibits/1
  # GET /exhibits/1.json
  def show
    @exhibits = Exhibit.all
    set_actual_exp @exhibit #para conhecer o atual exposição e mudar o menu

    #impressionst
    impressionist(@exhibit, "show inside exhibiti #{@exhibit.cidade}") 

    @gabinete_objects = @exhibit.gabinete_objects.paginate(page: params[:page], :per_page => 4)
    @gabinete_objects_all = @exhibit.gabinete_objects;
    @comentarios = @exhibit.comments.all

    @fotos_cidade = []
    @fotos_montagem = []
    @fotos_exposicao = []
    @fotos_natureza = []
    @fotos_coleta = []
    @exhibit.photos.each do |ima|
      @imagem_portada = ima if ima.ecapa == true
      @fotos_cidade << ima if ima.cidade == true
      @fotos_montagem << ima if ima.montagem == true
      @fotos_exposicao << ima if ima.expo == true
      @fotos_natureza << ima if ima.natureza == true
      @fotos_coleta << ima if ima.coleta == true
    end

  end

  # GET /exhibits/new
  def new
    @exhibit = Exhibit.new
  end

  # GET /exhibits/1/edit
  def edit
    @gabinete_object = @exhibit.gabinete_objects.build
  end

  # POST /exhibits
  # POST /exhibits.json
  def create
    @exhibit = Exhibit.new(exhibit_params)

    respond_to do |format|
      if @exhibit.save
        format.html { redirect_to creation_exhibits_path, notice: 'Exhibit was successfully created.' }
        format.json { render :show, status: :created, location: @exhibit }
      else
        format.html { render :new }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibits/1
  # PATCH/PUT /exhibits/1.json
  def update
    respond_to do |format|
      if @exhibit.update(exhibit_params)
        format.html { redirect_to @exhibit, notice: 'Exhibit was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibit }
      else
        format.html { render :edit }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibits/1
  # DELETE /exhibits/1.json
  def destroy
    @exhibit.destroy
    respond_to do |format|
      format.html { redirect_to creation_exhibits_url, notice: 'Exhibit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibit
      @exhibit = Exhibit.find(params[:id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibit_params
      params.require(:exhibit).permit(:cidade, :datainicio, :datafim, :local, :map, :descripcion, :video_src, :public)
    end
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
  
  def set_actual_exp(exp)
    @exp = exp
  end
  def get_actual_exp
    @exp
  end

  def get_exposicoes
    Exhibit.all
  end

  def def_actual_exhibit (exh)
    session[:exh_id] = exh.id
#    @actO = GabineteObject.find_by(id: obj.id)
  end

  def get_actual_exhibit
    exh_id = session[:exh_id]
    @actE = Exhibit.find_by(id: exh_id)
  end


  def no_actual_exhibit
    session.delete(:exh_id)
  end

end

app/views/exhibits/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@exhibit) do |f| %>
      <% if @exhibit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@exhibit.errors.count, "error") %> prohibited this exhibit from being saved:</h2>
    
          <ul>
          <% @exhibit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= f.label :cidade %><br>
        <%= f.text_field :cidade %>
      </div>
      <div class="field">
        <%= f.label :datainicio %><br>
        <%= f.text_field :datainicio %>
      </div>
      <div class="field">
        <%= f.label :datafim %><br>
        <%= f.text_field :datafim %>
      </div>
      <div class="field">
        <%= f.label :local %><br>
        <%= f.text_field :local %>
      </div>
      <div class="field">
        <%= f.label 'descripção' %><br>
        <%= f.text_area :descripcion %>
      </div>
      <div class="field">
        <%= f.label 'link do video' %><br>
        <%= f.text_field :video_src %>
      </div>
      <div class="field">
        <%= f.label :map %><br>
        <%= f.text_field :map, placeholder:'link com de google map para ser embedido. em Options -> share or embed map. E colar aqui o endereço' %>
      </div>
      <div class="field">
        <%= f.label 'publicar exposição' %><br>
        <%= f.check_box :public %>
      </div>
      <div class="field">
      <div class="actions">
        <%= f.submit params[:action]+' exposição', class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

app/views/exhibits/_gabinete_objects.html.erb
<li id="gabinete_object-<%= gabinete_object.id %>" >
            <div class="row">
              <div class="col-md-6">
                <% pic = gabinete_object.photos.first.picture if gabinete_object.photos.any?%>
                <span class="content">
                <%= image_tag pic.url  if !pic.nil? %>
                </span>
              </div>
              <div class="col-md-6">
                <div class="row">
                    <h1>  <%= gabinete_object.nome %> </h1>
                  </div>
                <div class="row">
                  <h2> <%= gabinete_object.pessoa %> |
                  <%= gabinete_object.idade %> </h2>
              </div>
          </div>
        </li>

app/views/exhibits/creation.html.erb
<div class="container bg-info">
  <p id="notice"><%= notice %></p>
</div>

<h1>Lista de Exposições</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table">
      <thead>
        <tr>
          <th>Cidade</th>
          <th>Datainicio</th>
          <th>Datafim</th>
          <th>Local</th>
          <th>Foto de expo</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @exhibits.each do |exhibit| %>
          <tr>
            <td><%= exhibit.cidade %></td>
            <td><%= exhibit.datainicio %></td>
            <td><%= exhibit.datafim %></td>
            <td><%= exhibit.local %></td>
            <td><%= link_to 'Sube foto', new_photo_path(:exhibit => exhibit), class:'btn btn-success' %> </td>
            <td><%= link_to 'Sube comentario', new_comment_path(:exhibit => exhibit), class:'btn btn-success' %> </td>
            <td><%= link_to 'Show', exhibit %></td>
            <td><%= link_to 'Edit', edit_exhibit_path(exhibit) %></td>
            <td><%= link_to 'Destroy', exhibit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <tr>
            <td colspan="9"> <%= link_to 'Subir objeto', new_gabinete_object_path(:exhibit => exhibit), class:'btn btn-primary' %> </td>
          </tr>
          <tr>
            <td colspan="9"> Visitas só contando a primeira vez que entra: <%= "#{exhibit.impressionist_count(:filter=>:session_hash)} " %> </td>
          </tr>
          <tr>
            <td colspan="9"> Todas as visitas: <%= "#{exhibit.impressionist_count()} " %> </td>
          </tr>
          <tr>
            <td colspan="7"> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p> <%= link_to 'Nova exposição', new_exhibit_path, class:'btn btn-success' %> </p>
  </div>
</div>
<br>

<h1>Visitas</h1>

<h2>Outras listas</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'Lista de objetos', creation_gabinete_objects_path, class:'btn btn-info' %>
    <hr>
    <%= link_to 'Lista de imagens', creation_photos_path, class:'btn btn-info' %>
    <hr>
    <%= link_to 'Lista de historias', creation_histories_path, class:'btn btn-info' %>
  </div>
</div>

app/views/exhibits/edit.html.erb
<h1>Edição da exposição</h1>

<%= render 'form' %>

<!-- <h1>Crear un nuevo objeto en la exposicion</h1> -->
<!-- <%= render 'gabinete_objects/form' %> -->

<div class="container">
<%= link_to 'Show', @exhibit %> |
<%= link_to 'Back', creation_exhibits_path %>
</div>

app/views/exhibits/index.html.erb
<h1>Exposições</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table">
      <thead>
        <tr>
          <th>Cidade</th>
          <th>Datainicio</th>
          <th>Datafim</th>
          <th>Local</th>
        </tr>
      </thead>
    
      <tbody>
        <% @exhibits.each do |exhibit| %>
          <tr>
            <td><%= exhibit.cidade %></td>
            <td><%= exhibit.datainicio %></td>
            <td><%= exhibit.datafim %></td>
            <td><%= exhibit.local %></td>
          </tr>
          <tr>
            <td colspan="4"> <%= link_to 'Ir a exposição', exhibit, class:'btn btn-primary' %> </td>
          </tr>
          <tr>
            <td colspan="4"> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/exhibits/new.html.erb
<h1>New Exhibit</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibits_path %>

app/views/exhibits/show.html.erb
<% content_for :meta_tags do %>
  <% if !@fotos_exposicao.first.nil? %>
    <meta property="og:image" content="<%=  @fotos_exposicao.first.picture.url %>" />
  <% end %>

  <% if !@exhibit.nil? %>
    <meta property="og:description"  content=" do <%= @exhibit.datainicio %> à <%= @exhibit.datafim %> | <%= @exhibit.local %> " />
    <meta content="<%= @exhibit.cidade.upcase %> | Exposição de Objetos significativos | Gabinete das Lembranças" property="og:title">
  <% else %>
    <meta property="og:description"  content="Colectivo Infinitos Monos | O Gabinete das Lembranças é uma exposição de objetos significativos e suas memórias. Cada exposição é fruto de uma residência de 10 dias em cada cidade envolvida. Nesse tempo a equipe coleta objetos e histórias entre os moradores que querem participar e serem parte da exposição." />
    <meta content="Gabinete das Lembranças" property="og:title">
  <% end %>
<% end %>

<!-- IMAGEM DE INICIO -->
 <div id="inicio-pag" class="expo-ini" style="background: url('<%=@imagem_portada.picture.url if !@imagem_portada.nil? %>') no-repeat center center fixed; ">
  <div class="espaco-imagem">
  <h1> </h1>
  </div>
</div>

<!-- INFO DA CIDADE -->
<div id="cidade" class="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center ">
        <h1 class="titulo" style="font-size: 6em"> <%= @exhibit.cidade.upcase %> </h1>
        <h4 class="texto-interno"> do <%= @exhibit.datainicio %> à <%= @exhibit.datafim %> </h4>
        <h4 class="texto-interno"> <%= @exhibit.local %> </h4>
      </div>
    </div>
    <!-- /.row -->
  </div>
</div>

  <!-- Map -->
<div class="map">
  <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="<%= @exhibit.map %>"></iframe>
    <br />
</div>
<br><br><br>

<!-- VIDEO -->
<% if !@exhibit.video_src.blank? %>
    <div class='myIframe' id="video-expo" >
      <iframe src="<%=@exhibit.video_src %>" frameborder="0" allowfullscreen></iframe>
    </div>
  <br>
<% end %>

<!-- SOCiAL NETWORKS -->
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-5">
      <% if !@imagem_portada.nil? %>
        <h3 class="titulo-int"> <    Compartilha essa exposição   >  </h3>
        <%= social_share_button_tag("#{@exhibit.cidade}  | Bahia | Exposição de objetos significativos", :image => @imagem_portada.picture.url , :'data-type' => 'photo', 'data-twitter-title' => "#{@exhibit.cidade}  | Bahia | Gabinete das Lembranças", :via => "Javingka") %>
      <% end %>
    </div>
  </div>
</div>
<br>


<!-- TITULO PARA MOSTRA DA EXPOSIÇÃO   -->
<div id="a-expo" class="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 ">
        <h3 class="titulo-int text-center"> A EXPOSIÇÃO </h3>
        <p class="texto-interno"><%=simple_format(@exhibit.descripcion) %></p>
      </div>
    </div>
    <!-- /.row -->
  </div>

  <!-- carousel ================================================== -->
  <div id="mycarousel" class="carousel slide" data-ride="carousel">
    <!-- indicators -->
    <ol class="carousel-indicators">
      <% @fotos_exposicao.count.times do |index| %>
        <% if index == 0 %>
          <li data-target="#mycarousel" data-slide-to=<%= index %> class='active' ></li>
        <% else %>
          <li data-target="#mycarousel" data-slide-to=<%= index %>> </li>
        <% end %>
      <% end %>
    </ol>
    <div class="carousel-inner" role="listbox">
      <% @fotos_exposicao.each_with_index do |f, index| %>
        <% if index == 0 %>
          <div class="item active">
        <% else %>
          <div class="item">
        <% end %>
          <%= image_tag f.picture.url %>
        </div>
      <% end %>
    </div>
     <a class="left carousel-control" href="#mycarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">previous</span>
    </a>
    <a class="right carousel-control" href="#mycarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">next</span>
    </a>
  </div>
</div>

<!-- GALERIA NOVA -->
<h2 class="titulo-int " style="text-align: center">OBJETOS E SUAS HISTÓRIAS </h2>
<div id="galeria-obj" class="container-fluid" >
  <% if @gabinete_objects_all.any? %>
  <div class="row">
    <% @gabinete_objects_all.each_with_index do |gabinete_object, index| %>
        <% gabinete_object.photos.each do |ima| %>
          <% @imagem_portada_o = ima if ima.ocapa == true %>
        <%end%>
        <% if !@imagem_portada_o.nil? %>
          <% pic = @imagem_portada_o.picture  %>
          <% @imagem_portada_o = nil %>
        <% else %>
          <% pic = gabinete_object.photos.first.picture if gabinete_object.photos.any?%>
        <% end %>

        <% his = gabinete_object.histories.first.frase if gabinete_object.histories.any?%>


        <% if !pic.nil? %>
          <% if @gabinete_objects_all.count % 2 != 0 && index == @gabinete_objects_all.count-1 %>
          <div id ="gal-obj_<%= index %>" class="img-gal col-xs-12 col-sm-12 " style="background-image: url(<%= pic.url %>);  background-repeat: no-repeat;  background-position: center;  max-height:330px"> <!-- background-size: 100%; -->'

          <% else %>
          <div id ="gal-obj_<%= index %>" class="img-gal col-xs-12 col-sm-6 col-md-6"
             style="background-image: url(<%= pic.url %>);  background-repeat: no-repeat;  background-position: center;
             height:auto"> <!-- background-size: 100%; -->'
          <% end %>
     <!--          <%= link_to image_tag( pic.url, width:'100%' ), gabinete_object %> -->
        <% else %>
          <div id ="gal-obj_<%= index %>" class="img-gal col-xs-6 col-md-6" style="background-color: gray ">
        <% end %>
        <!-- Texto sobre a imagem com história -->
          <div id ="info-obj_<%= index %>" class="preview-objeto" style="background-color: rgba(0,0,0,.7); visibility: hidden; border-radius:50px">
            <h3 class="titulo-int" style="color: rgb(220,220,220); text-align: center; margin-top: 5px" >
               <strong> <%= gabinete_object.nome.upcase %> </strong> </h3>
            <h4 class="titulo-int" style="color: rgb(200,200,200); text-align: center" > <%= gabinete_object.pessoa %> |
            <%= gabinete_object.idade %> anos </h4>
            <p class="his-preview texto-interno" style="color: white; font-size:15px; margin: 5px" >
               <i> <%= his if !his.nil? %></i> </p>
            <div class="row">
            <div class="col-xs-8 col-xs-offset-2" >
              <%= link_to 'ver mais', gabinete_object, class:'btn btn-primary titulo-int', method:'get',
               style:"color: #fff;background-color: rgba(0,0,0,.9); margin-top: 5px; margin-bottom: 20px; border-color: #999 " %>
            </div>
            </div>
          </div>
        </div>
    <% end %>
  <% end %>
  </div>
<br><br>
</div>

<%= javascript_tag do %>
  var ig = $(".img-gal");
  var w = ig.width();
  w = w/2;
//  alert ("w" + w);
  ig.css('height', w);

  $(".img-gal").hover( function (event) {
    var numberOut = /[0-9]+/; //tw tiene el formato: 000px, con el número seguido de 'px'
    var id = numberOut.exec(event.target.id); //nos quedamos solo con los números
    var id_o = "info-obj_"+id;
    var visibilidad = document.getElementById(id_o).style.visibility;
//    if (visibilidad == 'visible')
//      document.getElementById(id_o).style.visibility = "hidden";
//    else
      document.getElementById(id_o).style.visibility = "visible";
    },  function (event) {
    var numberOut = /[0-9]+/; //tw tiene el formato: 000px, con el número seguido de 'px'
    var id = numberOut.exec(event.target.id); //nos quedamos solo con los números
    var id_o = "info-obj_"+id;
    var visibilidad = document.getElementById(id_o).style.visibility;
//    if (visibilidad == 'visible')
      document.getElementById(id_o).style.visibility = "hidden";
//    else
//      document.getElementById(id_o).style.visibility = "visible";
  }
  );
  $(".img-gal").mouseenter( function (event) {

  });

<% end %>

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="expo-gallery" class="container-fluid">
<div class='jumbotron row'>
  <h2 class="titulo-int">GALERIA DE IMAGENS </h2>
  <br>
  <div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="links">
  <% @fotos_montagem.each do |f| %>

    <div class="col-lg-3 col-md-4 col-xs-6 thumb" style="background-image: url(<%= f.picture.url %>);  background-repeat: no-repeat;  background-position: center; background-size: 180%;  height:auto">
      <a href="<%= f.picture.url %>" style="background-color: transparent; height:150px; border-style: none" class= "thumbnail" title=" " data-gallery>
      </a>
    </div>
  <% end %>
  <% @fotos_exposicao.each do |f| %>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb" style="background-image: url(<%= f.picture.url %>);  background-repeat: no-repeat;  background-position: center; background-size: 180%;  height:auto">
      <a href="<%= f.picture.url %>" style="background-color: transparent; height:150px; border-style: none" class= "thumbnail" title=" " data-gallery>
      </a>
    </div>
  <% end %>
   <% @fotos_coleta.each do |f| %>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb" style="background-image: url(<%= f.picture.url %>);  background-repeat: no-repeat;  background-position: center; background-size: 180%;  height:auto">
      <a href="<%= f.picture.url %>" style="background-color: transparent; height:150px; border-style: none" class= "thumbnail" title=" " data-gallery>
      </a>
    </div>
  <% end %>
  <% @fotos_cidade.each do |f| %>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb" style="background-image: url(<%= f.picture.url %>);  background-repeat: no-repeat;  background-position: center; background-size: 180%;  height:auto">
      <a href="<%= f.picture.url %>" style="background-color: transparent; height:150px; border-style: none" class= "thumbnail" title=" " data-gallery>
      </a>
    </div>
  <% end %>
</div>
</div>

<div id='comentarios' class='jumbotorn'>
  <h1 class='titulo-int'> LIVRO DE VISITAS </h1>

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table">
        <thead>
          <tr>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% blankCom = [] %>
          <% soNomeCom = [] %>
          <% @comentarios.each do |comment| %>
            <% if comment.exhibit_id == @exhibit.id %>
              <% if comment.pessoa.blank? %>
                <% blankCom << comment %>
                <% next %>
              <% elsif comment.pessoa !~ /[0-9]/ %>
                <% soNomeCom << comment %>
                <% next %>
              <% end %>
              <tr>
                <td  class="titulo-int"><%= comment.comentario %> <%= comment.pessoa %> </td>
              </tr>
            <% end %>
          <% end %>
          <% soNomeCom.each do |comment| %>
             <tr><td class="titulo-int"><%= comment.comentario %> <%= comment.pessoa %> </td> </tr>
          <% end %>
          <% blankCom.each do |comment| %>
            <tr><td class="titulo-int"><%= comment.comentario %> </td> </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br>
</div>

<!-- Counter -->
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-5 ">
        <p>
          <!-- (         <%= "#{@exhibit.impressionist_count(:filter=>:session_hash)} visitas" %>)  -->
        </p>
    </div>
  </div>
  </div>


<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>

<script>
  $('.carousel').carousel({
   interval: 3000
  });
  $(document).on('ready page:load', function () {
    // Actions to do
    navigationFn.goToSection('#cidade');
  });

  var navigationFn = {
    goToSection: function(id) {
    $('html, body').animate({
        scrollTop: $(id).offset().top
      }, 2000);
    }
  }
</script>