config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :exhibits do
    collection do
      get 'creation'
    end
  end
  resources :gabinete_objects do
    collection do
      get 'creation'
    end
    member do
      get :acbeu
    end
  end
  resources :histories do
    collection do
      get 'creation'
    end
  end
  resources :photos do
    collection do
      get 'creation'
    end
  end

  resources :comments do
    collection do
      get 'creation'
    end
  end

  get 'static_pages/home'
  get 'static_pages/monos'
  get 'static_pages/show_exp'
  get 'static_pages/acbeu'
  match "/depoimentos" => "static_pages#acbeu", via: :get

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :gabinete_object
  validates :gabinete_object, presence: true

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  def creation
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @objeto = GabineteObject.find(params[:gabinete_object])
    @history = @objeto.histories.build
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @objeto = GabineteObject.find(params[:history][:gabinete_object_id])
    @history = @objeto.histories.build(history_params)
    exh = Exhibit.find_by(id: @objeto.exhibit_id) 
    respond_to do |format|
      if @history.save
        format.html { redirect_to new_photo_path(:gabinete_object => @objeto, :exhibit => exh ), notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to creation_histories_path, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to creation_histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:memoria, :gabinete_object_id, :frase)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@history) do |f| %>
      <% if @history.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>
    
          <ul>
          <% @history.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= f.label :memoria %><br>
        <%= f.text_area :memoria %>
      </div>

      <div class="field">
        <%= f.label :frase %><br>
        <%= f.text_area :frase, placeholder:'a frase fica como preview na lista de objetos. não mais de 140 caracteres' %>
      </div>
      
      <%= f.hidden_field :gabinete_object_id, :value => @objeto.id if !@objeto.nil? %>
      <div class="actions">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/histories/creation.html.erb
<div class="container bg-info">
  <p id="notice"><%= notice %></p>
</div>

<h1>Lista de historias de objetos</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <table class="table">
     <thead>
        <tr>
          <th>frase inicial</th>
          <th> <%= link_to 'Objetos', creation_gabinete_objects_path, class: 'btn btn-default' %> </th>
          <th> <%= link_to 'Exposiçoes', creation_exhibits_path, class: 'btn btn-default' %></th>
          <th>ver completa </th>
          <th>editar</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @histories.each do |history| %>
          <% obj = GabineteObject.find_by(id: history.gabinete_object_id) %>
          <% exp = Exhibit.find_by(id: obj.exhibit_id) %>
          <tr>
            <td><%= history.frase %></td>
            <td><%= link_to obj.nome, gabinete_object_path(obj)  , class: 'btn btn-link' %> </td>
            <td><%= link_to_if !exp.nil?, exp.cidade, exhibit_path(exp) , class: 'btn btn-link'%> </td>
            <td><%= link_to 'Show', history %></td>
            <td><%= link_to 'Edit', edit_history_path(history) %></td>
            <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

app/views/histories/edit.html.erb
<h1>Edição da historia</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', creation_histories_path %>

app/views/histories/index.html.erb
<div class="container bg-info">
  <p id="notice"><%= notice %></p>
</div>

<h1>Lista de historias de objetos</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table">
     <thead>
        <tr>
          <th>Memoria</th>
          <th> <%= link_to 'Objetos', gabinete_objects_path, class: 'btn btn-default' %> </th>
          <th> <%= link_to 'Exposiçoes', exhibits_path, class: 'btn btn-default' %></th>
        </tr>
      </thead>
    
      <tbody>
        <% @histories.each do |history| %>
          <% obj = GabineteObject.find_by(id: history.gabinete_object_id) %>
          <% exp = Exhibit.find_by(id: obj.exhibit_id) %>
          <tr>
            <td><%= history.memoria %></td>
            <td><%= link_to obj.nome, gabinete_object_path(obj)  , class: 'btn btn-link' %> </td>
            <td><%= link_to_if !exp.nil?, exp.cidade, exhibit_path(exp) , class: 'btn btn-link'%> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

app/views/histories/new.html.erb
<h1> Nueva memoria para <%= @objeto.nome %>  </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>
      Descripción del objeto: <%= @objeto.descripcao %>
    </p>
  </div>
</div>
    <%= render 'form' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'Back', histories_path , class: 'btn btn-secundary'%>
  </div>
</div>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Memoria:</strong>
  <%= @history.memoria %>
</p>

<p>
  <strong>Gabinete object:</strong>
  <%= @history.gabinete_object %>
</p>

<%= link_to 'Back', histories_path %>