config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :exhibits do
    collection do
      get 'creation'
    end
  end
  resources :gabinete_objects do
    collection do
      get 'creation'
    end
    member do
      get :acbeu
    end
  end
  resources :histories do
    collection do
      get 'creation'
    end
  end
  resources :photos do
    collection do
      get 'creation'
    end
  end

  resources :comments do
    collection do
      get 'creation'
    end
  end

  get 'static_pages/home'
  get 'static_pages/monos'
  get 'static_pages/show_exp'
  get 'static_pages/acbeu'
  match "/depoimentos" => "static_pages#acbeu", via: :get

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :gabinete_object
  belongs_to :exhibit
#  validates :exhibit, presence: true
#  validates :gabinete_object, presence: true
  mount_uploader :picture, PictureUploader
  validate :picture_size

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, 'a imagem tem que ser menor que 5MB')
      end
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  def creation
    @photos = Photo.paginate(page: params[:page], :per_page => 30)
  #  @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    if !params[:exhibit].nil?
      @exhibit = Exhibit.find(params[:exhibit])
      @photo = @exhibit.photos.build
    end
    if !params[:gabinete_object].nil?
      @objeto = GabineteObject.friendly.find(params[:gabinete_object])
      @photo = @objeto.photos.build
    end
  end

  # GET /photos/1/edit
  def edit
    @exhibit = Exhibit.find_by(id: @photo.exhibit_id)
    @objeto = GabineteObject.friendly.find_by(id: @photo.gabinete_object_id)
  end

  # POST /photos
  # POST /photos.json
  def create
    if !params[:photo][:gabinete_object_id].nil?
      @objeto = GabineteObject.friendly.find(params[:photo][:gabinete_object_id])
      @photo = @objeto.photos.build(photo_params)
    end
    if !params[:photo][:exhibit_id].nil?
      @exhibit = Exhibit.find(params[:photo][:exhibit_id])
      @photo = @exhibit.photos.build(photo_params)
    end

    respond_to do |format|
       if @photo.save
         format.html { redirect_to creation_photos_path, notice: 'A imagem foi criada corretamente.' }
         format.json { render :show, status: :created, location: @photo }
       else
         format.html { render :new }
         format.json { render json: @photo.errors, status: :unprocessable_entity }
       end
    end

  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to creation_photos_url, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:picture, :exhibit_id, :gabinete_object_id, :ecapa, :ocapa, :montagem, :expo, :cidade, :natureza, :coleta, :cara)
    end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@photo, html: { multipart: true }) do |f| %>
      <% if @photo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
    
          <ul>
          <% @photo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpg,image/jpeg,image/gif,image/png' %>
      </span>

  <div class="checkbox">
      <% if !@exhibit.nil? %>
        <%= f.label :ecapa do %>
          <%= f.check_box :ecapa %> Check se é a imagem capa da residencia 
        <% end %> <br>
        <%= f.label :montagem do %>
          <%= f.check_box :montagem %> Check se é imagem da montagem 
        <% end %> <br>
        <%= f.label :expo do %>
          <%= f.check_box :expo %> Check se é imagem da exposição
        <% end %> <br>
        <%= f.label :cidade do %>
          <%= f.check_box :cidade %> Check se é imagem da cidade
        <% end %> <br>
        <%= f.label :natureza do %>
          <%= f.check_box :natureza %> Check se é imagem de natureza
        <% end %> <br>
        <%= f.label :coleta do %>
          <%= f.check_box :coleta %> Check se é imagem de coleta
        <% end %>
      <% end %>
  </div>
  <hr>

  <div class="checkbox">
      <% if !@objeto.nil? %>
        <%= f.label :ocapa do %>
          <%= f.check_box :ocapa %> Check se é a imagem da capa do objeto?
        <% end %> <br>
        <%= f.label :cara do %>
          <%= f.check_box :cara %> Check se é imagem da cara da pessoa
        <% end %>
      <% end %>
    </div>

      <%= f.hidden_field :gabinete_object_id, :value => @objeto.id if !@objeto.nil? %>
      <%= f.hidden_field :exhibit_id        , :value => @exhibit.id if !@exhibit.nil? %>

      <div class="field">
      </div>
      <div class="actions">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>


<script type="text/javascript">
  $('#photo_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Oi mono!!.. O que foi??  ...O tamanho máximo para o arquivo é de 5MB. Escolhe um menor e vai pular nos galhos');
    }
  });
</script>

app/views/photos/creation.html.erb
<div class="container bg-info">
  <p id="notice"><%= notice %></p>
</div>

<h1>Lista de imagenes</h1>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
<%= will_paginate @photos %>
    <table class="table">
      <thead>
        <tr>
          <th>Picture</th>
          <th>Capa de Exposição</th>
          <th>Capa de Objeto</th>
          <th>montagem</th>
          <th>exposição</th>
          <th>cidade</th>
          <th>natureza</th>
          <th>coleta</th>
          <th>cara</th>
          <th> <%= link_to 'Objetos', creation_gabinete_objects_path, class: 'btn btn-default' %> </th>
          <th> <%= link_to 'Exposiçoes', creation_exhibits_path, class: 'btn btn-default' %></th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @photos.each do |photo| %>
          <% obj = GabineteObject.find_by(id: photo.gabinete_object_id) %>
          <% exp = Exhibit.find_by(id: photo.exhibit_id) %>
          <tr>
            <td><%= image_tag photo.picture.url, size:'100x100' %></td>
            <td><%= photo.ecapa ? 'X' : '-' %></td>
            <td><%= photo.ocapa ? 'X' : '-' %></td>
            <td><%= photo.montagem ? 'X' : '-' %></td>
            <td><%= photo.expo ? 'X' : '-' %></td>
            <td><%= photo.cidade ? 'X' : '-' %></td>
            <td><%= photo.natureza ? 'X' : '-' %></td>
            <td><%= photo.coleta ? 'X' : '-' %></td>
            <td><%= photo.cara ? 'X' : '-' %></td>
            <% if !obj.nil? %>
            <td><%= link_to obj.nome, gabinete_object_path(obj)  , class: 'btn btn-link' %> </td>
          <% else %>
            <td> </td>
          <% end %>
            <td><%= link_to_if !exp.nil?, exp.cidade, exhibit_path(exp) , class: 'btn btn-link'%> </td>
            <td><%= link_to 'Show', photo %></td>
            <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
            <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<%= will_paginate @photos %>
  </div>
</div>
<br>

app/views/photos/edit.html.erb
<h1>Edição de imagem</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', creation_photos_path %>

app/views/photos/index.html.erb
<div class="container bg-info">
  <p id="notice"><%= notice %></p>
</div>

<h1>Lista de imagenes</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table">
      <thead>
        <tr>
          <th>Picture</th>
          <th> <%= link_to 'Objetos', gabinete_objects_path, class: 'btn btn-default' %> </th>
          <th> <%= link_to 'Exposiçoes', exhibits_path, class: 'btn btn-default' %></th>
        </tr>
      </thead>
    
      <tbody>
        <% @photos.each do |photo| %>
          <% obj = GabineteObject.find_by(id: photo.gabinete_object_id) %>
          <% exp = Exhibit.find_by(id: photo.exhibit_id) %>
          <tr>
            <td><%= photo.picture %></td>
            <% if !obj.nil? %>
            <td><%= link_to obj.nome, gabinete_object_path(obj)  , class: 'btn btn-link' %> </td>
          <% else %>
            <td> </td>
          <% end %>
            <td><%= link_to_if !exp.nil?, exp.cidade, exhibit_path(exp) , class: 'btn btn-link'%> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/photos/new.html.erb
<% obj = exh = '' %>
<% if !@objeto.nil? %>
  <% obj = @objeto.nome %>
<% end %>
<% if !@exhibit.nil? %>
  <% exh = @exhibit.cidade %>
<% end %>

<h1> Nueva Foto </h1>
<h2> <%= exh %>  </h2>
<h2> <%= obj %>  </h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if obj != '' %>
    <p>
      Descripción del objeto: <%= @objeto.descripcao %>
    </p>
  <% end %>
  </div>
</div>
    <%= render 'form' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'Back' , creation_photos_path , class: 'btn btn-secundary'%>
  </div>
</div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
</p>
    <%= image_tag @photo.picture.url  %>
<p>
  <strong>Gabinete object:</strong>
  <%= @photo.gabinete_object_id %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>