config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :exhibits do
    collection do
      get 'creation'
    end
  end
  resources :gabinete_objects do
    collection do
      get 'creation'
    end
    member do
      get :acbeu
    end
  end
  resources :histories do
    collection do
      get 'creation'
    end
  end
  resources :photos do
    collection do
      get 'creation'
    end
  end

  resources :comments do
    collection do
      get 'creation'
    end
  end

  get 'static_pages/home'
  get 'static_pages/monos'
  get 'static_pages/show_exp'
  get 'static_pages/acbeu'
  match "/depoimentos" => "static_pages#acbeu", via: :get

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/gabinete_object.rb
class GabineteObject < ActiveRecord::Base
  belongs_to :exhibit
  has_many :photos, :dependent => :destroy
  has_many :histories, :dependent => :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  validates :expo_ID, uniqueness: true
  extend FriendlyId
  friendly_id :nome, use: :slugged
end

app/controllers/gabinete_objects_controller.rb
class GabineteObjectsController < ApplicationController
  before_action :set_gabinete_object, only: [:show, :edit, :update, :destroy]

  # GET /gabinete_objects
  # GET /gabinete_objects.json
  def index
    @gabinete_objects = GabineteObject.all
    @exh 
  end

  def acbeu
  
    render 'show_acbeu'
  end

  def creation
    @gabinete_objects = GabineteObject.all
  end

  # GET /gabinete_objects/1
  # GET /gabinete_objects/1.json
  def show
    @gabinete_objects = GabineteObject.all
    @expo = Exhibit.find_by(id: @gabinete_object.exhibit_id)
    set_actual_obj(@gabinete_objects, @expo)
    
    @fotos = @gabinete_object.photos.all
    @historia = @gabinete_object.histories.all
    @gabinete_object.photos.each do |ima|
      @imagem_portada = ima if ima.ocapa == true
      @imagem_cara = ima if ima.cara == true
    end
  end

  # GET /gabinete_objects/new
  def new
    @exhibit = Exhibit.find(params[:exhibit])
    @gabinete_object = @exhibit.gabinete_objects.build
#    no_actual_exhibit
#    @gabinete_object = GabineteObject.new
  end

  # GET /gabinete_objects/1/edit
  def edit
  end

  # POST /gabinete_objects
  # POST /gabinete_objects.json
  def create
    @exhibit = Exhibit.find(params[:gabinete_object][:exhibit_id])
    @gabinete_object =@exhibit.gabinete_objects.build(gabinete_object_params)

    respond_to do |format|
      if @gabinete_object.save
        format.html { redirect_to new_history_path(:gabinete_object => @gabinete_object), notice: 'Gabinete object was successfully created.' }
        format.json { render :show, status: :created, location: @gabinete_object }
      else
        format.html { render :new }
        format.json { render json: @gabinete_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gabinete_objects/1
  # PATCH/PUT /gabinete_objects/1.json
  def update
    respond_to do |format|
      if @gabinete_object.update(gabinete_object_params)
        format.html { redirect_to creation_gabinete_objects_path, notice: 'Gabinete object was successfully updated.' }
        format.json { render :show, status: :ok, location: @gabinete_object }
      else
        format.html { render :edit }
        format.json { render json: @gabinete_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gabinete_objects/1
  # DELETE /gabinete_objects/1.json
  def destroy
    @gabinete_object.destroy
    respond_to do |format|
      format.html { redirect_to creation_gabinete_objects_url, notice: 'Gabinete object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gabinete_object
      @gabinete_object = GabineteObject.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gabinete_object_params
      params.require(:gabinete_object).permit(:nome, :descripcao, :pessoa, :idade, :expo_ID, :audio_link, :video_src )
    end
end

app/helpers/gabinete_objects_helper.rb
module GabineteObjectsHelper
    
  def set_actual_obj(obj, expo)
    @obj = obj
    @exp_obj = expo
    next_o = false 
    @obj_n = nil 
    @exp_obj.gabinete_objects.each_with_index do |o,i| 
      puts 'prints:  '+@gabinete_object.id.to_s+' obj o: '+o.id.to_s
      if next_o 
        @obj_n = GabineteObject.friendly.find(o.id) #Precisamos pegar o objeto usando friendly url 
        #@obj_n = o 
        break 
      end 
      if o.id == @gabinete_object.id  #Se o id do objeto 'o' é o mesmo id do objeto de entrada 'obj' 
        next_o = true 
 #Pega o objeto seguinte do atual. Se for a ultima volta do loop. Não terá seguinte então o @obj_n tem que pegar seu valor do primeiro elemento da lista
        @obj_n = GabineteObject.friendly.find(@exp_obj.gabinete_objects.first.id) if i == @exp_obj.gabinete_objects.size-1 #Precisamos pegar o objeto usando friendly url 
        #@obj_n = o 
      end 
    end
  end
  
  def get_actual_obj
    @obj
  end

  def get_objects
    GabineteObject.all
  end

  def def_actual_object (obj)
    session[:obj_id] = obj.id
#    @actO = GabineteObject.find_by(id: obj.id)
  end

  def get_actual_object
    @obj_id = session[:obj_id]
    @actO = GabineteObject.find_by(@obj_id)
  end


  def no_actual_object
    session.delete(:obj_id)
  end

end

app/views/gabinete_objects/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@gabinete_object) do |f| %>
      <% if @gabinete_object.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@gabinete_object.errors.count, "error") %> prohibited this gabinete_object from being saved:</h2>
    
          <ul>
          <% @gabinete_object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= f.label :nome %><br>
        <%= f.text_field :nome, placeholder: 'O que objeto é?' %>
      </div>

      <%= f.hidden_field :exhibit_id, :value => @exhibit.id if !@exhibit.nil? %>
      <div class="field">
        <%= f.label :descripcao %><br>
        <%= f.text_area :descripcao, placeholder: 'É so uma descipção basico do objeto, não é a historia' %>
      </div>

      <div class="field">
        <%= f.label 'Pessoa' %><br>
        <%= f.text_field :pessoa, placeholder: 'Nome da pessoa dona do objeto' %>
      </div>

      <div class="field">
        <%= f.label :idade %>
        <%= f.text_field :idade, placeholder: 'Idade da pessoa' %>
      </div>

      <div class="field">
        <%= f.label :expo_ID %>
        <%= f.text_field :expo_ID, placeholder: 'Número na exposição ACBEU' %>
      </div>

      <div class="field">
        <%= f.label :audio_link %>
        <%= f.text_field :audio_link, placeholder: 'link con la ubicação na internet do arquivo de áudio' %>
      </div>

      <div class="field">
        <%= f.label :video_link %>
        <%= f.text_field :video_link, placeholder: 'link con la ubicação na internet do arquivo de video' %>
      </div>


      <div class="actions">
        <%= f.submit  class: "btn btn-primary"%>
      </div>

      <p class="text-info"> *A historia e as imagens são criadas depois de criar o objeto </p>
    <% end %>
  </div>
</div>

app/views/gabinete_objects/creation.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Objetos</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table">
      <thead>
        <tr>
          <th>Expo ID</th>
          <th>Nome</th>
          <th>Descripçao</th>
          <th> <%= link_to 'Exposiçoes', creation_exhibits_path, class: 'btn btn-default' %></th>
          <th>Numero de fotos</th>
          <th>Tem áudio?</th>
          <th>Tem vídeo?</th>
          <th>Tem imagem Rostro </th>
          <th>Nde memorias</th>
          <th>Dono(a)</th>
          <th>idade</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @gabinete_objects.each do |gabinete_object| %>
          <% exh = Exhibit.find_by(id: gabinete_object.exhibit_id) %>
          <tr>
            <td><%= gabinete_object.expo_ID %></td>
            <td><%= gabinete_object.nome %></td>
            <td><%= gabinete_object.descripcao %></td>
            <td><%= link_to_if !exh.nil?, exh.cidade, exhibit_path(exh) , class: 'btn btn-link'%> </td>
            <td><%= gabinete_object.photos.count %> Imgs </td>
            <td><%= !gabinete_object.audio_link.blank? ? 'c/audio' : 's/audio'  %> </td>
            <td><%= !gabinete_object.video_link.blank? ? 'c/audio' : 's/audio'  %> </td>
            <% fotoCara = '' %>
            <% gabinete_object.photos.each do |ima| %>
              <% ima.cara == true ? fotoCara = 'c/foto' : fotoCara = 's/foto' %>
            <% end %>
            <td><%= fotoCara %> </td>
            <td><%= gabinete_object.histories.count %>  hists</td>
            <td><%= gabinete_object.pessoa %> </td>
            <td><%= gabinete_object.idade %> </td>
            <td><%= link_to '+ foto', new_photo_path(:gabinete_object => gabinete_object, :exhibit => exh ), class:'btn btn-success' %> </td>
            <td><%= link_to '+ memoria', new_history_path(:gabinete_object => gabinete_object), class:'btn btn-success' %> </td>
            <td><%= link_to 'Show', gabinete_object %></td>
            <td><%= link_to 'Edit', edit_gabinete_object_path(gabinete_object) %></td>
            <td><%= link_to 'Destroy', gabinete_object, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

app/views/gabinete_objects/edit.html.erb
<h1>Editar Objeto</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

    <%= link_to 'Show', @gabinete_object %> |
    <%= link_to 'Back', creation_gabinete_objects_path %>
  </div>
</div>

app/views/gabinete_objects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Objetos</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Descripçao</th>
          <th> <%= link_to 'Exposiçoes', exhibits_path, class: 'btn btn-default' %></th>
        </tr>
      </thead>
    
      <tbody>
        <% @gabinete_objects.each do |gabinete_object| %>
          <% exh = Exhibit.find_by(id: gabinete_object.exhibit_id) %>
          <tr>
            <td><%= gabinete_object.nome %></td>
            <td><%= gabinete_object.descripcao %></td>
            <td><%= link_to_if !exh.nil?, exh.cidade, exhibit_path(exh) , class: 'btn btn-link'%> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

app/views/gabinete_objects/new.html.erb
<h1> Novo objeto para <%= @exhibit.cidade %> </h1>

<%= render 'form' %>

<%= link_to 'Back', gabinete_objects_path %>

app/views/gabinete_objects/show.html.erb
<% content_for :meta_tags do %>
  <% if !@imagem_portada.nil? %>
    <meta property="og:image" content="<%=  @imagem_portada.picture.url %>" />
  <% end %>

  <% his = @gabinete_object.histories.first.frase if @gabinete_object.histories.any?%>
  <% if !@gabinete_object.nil? %>
    <meta property="og:description"  content=" '<%= his if !his.nil? %>' " />
    <meta content="Gabinete das Lembranças. Objetos significativos | <%= @expo.cidade %> | <%= @gabinete_object.nome %> " property="og:title">
  <% else %>
    <meta property="og:description"  content="Colectivo Infinitos Monos | O Gabinete das Lembranças é uma exposição de objetos significativos e suas memórias. Cada exposição é fruto de uma residência de 10 dias em cada cidade envolvida. Nesse tempo a equipe coleta objetos e histórias entre os moradores que querem participar e serem parte da exposição." />
    <meta content="Gabinete das Lembranças" property="og:title">
  <% end %>
<% end %>


<!-- IMAGEM DE INICIO -->
<div class="expo-ini" style="background: url('<%=@imagem_portada.picture.url if !@imagem_portada.nil? %>') no-repeat center center fixed; "> 
  <div class="espaco-imagem"> 
  </div>
</div>

<div id="lembranca" class="container-fluid"></div>
<br >
<div class="container-fluid">
      <% if !@gabinete_object.video_link.blank? %>
          <div class='myIframe' id="video-expo" >
            <iframe src="<%=@gabinete_object.video_link %>" frameborder="0" allowfullscreen></iframe>
          </div>
        <br>
      <% end %>
      <% if !@gabinete_object.audio_link.nil? %>
        <hr>
          <div class="row" ><div class="col-xs-3 col-xs-offset-5">
          <div class="ui360 ui360-viz" >
            <a href="<%= @gabinete_object.audio_link %>"  onClick="reply_click(this.id)" id= "playpause-<%= @gabinete_object.nome %>" >
              <p class="titulo-int center" style="margin-left: 10px"><strong>    OUVIR </strong>Depoimento.</p>
            </a>
            <span style="position: absolute; margin:18px 0 0 10px" class="glyphicon glyphicon-headphones" aria-hidden="true"></span>
          </div>
        </div></div>
        <hr >
    <% end %>

  <div class="jumbotron row">
      <div id="historia" class="col-md-9">
       <h3>  </h3>
        <%=  simple_format(@gabinete_object.histories.first.memoria, class: "texto-interno") %>
      </div>
    <% if !@imagem_cara.nil? %>
      <div id="imgNome" class="col-md-3"style="background: url('<%=@imagem_cara.picture.url %>')no-repeat fixed; background-position: 600px center; height: 480; min-height:480px ">
    <% else %>
      <div class="col-md-3"style="background-color: rgba(50,50,50, .2) ">
    <% end %>
      <aside>
        <section class="user_info">
          <h1 class="titulo" style="color: white; font-size:2em"><%= @gabinete_object.pessoa %> </h1>
        </section>
        <section class="stats">
          <% if @gabinete_object.idade != '' %>
            <h2 class="titulo-int"style="color: white"> <%= @gabinete_object.idade %> anos </h2>
          <% end%>
        </section>
        <section>
          <h3 class="titulo-int"style="color: white"> <%= @gabinete_object.nome %></h3>
        </section>
      </br>
      </aside>
      </div>
   </div>
 </div>

 <!-- SOCIAL NETWORKS -->
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-5">
      <h3 class="titulo-int"> <    Compartilha essa lembrança   >  </h3>
      <% if !@imagem_portada.nil? %>
        <%= image_tag @imagem_portada.picture.url, hidden: true if @imagem_portada.picture? %>
        <%= social_share_button_tag("#{@gabinete_object.nome}  | #{@expo.cidade} | Gabinete das Lembranças", :image => @imagem_portada.picture.url , :'data-type' => 'photo', 'data-twitter-title' => "#{@gabinete_object.nome}  | #{@expo.cidade} | Gabinete das Lembranças", :via => "Javingka") %>
      <% end %>
    </div>
  </div>
</div>
<br>

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="imagen-obj" class="container-fluid">
<div class='jumbotron row'>
  <h2 class="titulo"> Imagens </h2>
  <br>
  <div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="links">
  <% @fotos.each do |f| %>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb" style="background-image: url(<%= f.picture.url %>);  background-repeat: no-repeat;  background-position: center; background-size: 100%;  height:auto">
      <a href="<%= f.picture.url %>" style="background-color: transparent; height:150px; border-style: none" class= "thumbnail" title=" " data-gallery>
      </a>
    </div>
  <% end %>
</div>
</div>


<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="js/bootstrap-image-gallery.min.js"></script>

<script>
$(document).on('ready page:load', function () {
   navigationFn.goToSection("#lembranca");
   var w = $(window).width();
   var imagw = $("#imgNome").width();
   var offsetP  = w - imagw - 120;
   var offsetPixels = offsetP + 'px center';
   $("#imgNome").css( 'background-position', offsetPixels );
   var minM=w;
   var maxM=w-imagw;


  // Actions to do
   var h = $("#historia").height();
   var ih = $("#imgNome").height();
   if ( ih < h )  $("#imgNome").height(h);

   $("#imgNome").mousemove(function( event ) {
     var mx = event.pageX ;
     if (mx < minM) minM = mx;
     else if (mx > maxM) maxM = mx;

     console.log("mx: " + mx + " OffsetP: "+ offsetP + " | MinM : " + minM + " maxM: " + maxM);
     var p = 1 - ( (mx - minM) / (maxM-minM) );
     p = offsetP - 60 + (p * -300);
     var bp = ( p +'px  center');
     console.log("backgroundpos: " + bp); 
     $("#imgNome").css( 'background-position', bp  );
   });
});

  $(document).ready(function(){  
});
    var navigationFn = {
    goToSection: function(id) {
        $('html, body').animate({
            scrollTop: $(id).offset().top
        }, 2000);
    }
   }
</script>

app/views/gabinete_objects/show_acbeu.html.erb
<% content_for :acbeu do %>

<h1>ABCEU OBJETO PAGINA </h1>

<% end %>

<script>
  soundManager.debugMode = false
  soundManager.flashVersion = 9
  soundManager.multiShot = false
  soundManager.url = "<%= asset_path('soundmanager2.swf') %>"
  soundManager.useHTML5Audio = true
  soundManager.consoleOnly = true


soundManager.setup({

    // where to find the SWF files, if needed
    url: '/path/to/swf-directory/',

    onready: function() {
      // SM2 has loaded, API ready to use e.g., createSound() etc.
      var mySound = soundManager.createSound({
          id: 'id_som',
          url: 'https://s3-sa-east-1.amazonaws.com/gabinete-lembrancas/audios/m/FOTOS_DISCO+VOADOR.mp3',
          // begin loading right away
          autoLoad: true,
          whileloading: function() {
            soundManager._writeDebug(this.id + ': loading ' + this.bytesLoaded + ' / ' + this.bytesTotal);
          }
         });
      mySound.play();
    },

    ontimeout: function() {
      // Uh-oh. No HTML5 support, SWF missing, Flash blocked or other issue
    }

});

threeSixtyPlayer.config = {
  playNext: false, // stop after one sound, or play through list until end
  autoPlay: false, // start playing the first sound right away
  allowMultiple: true, // let many sounds play at once (false = one at a time)
  loadRingColor: '#ccc',// amount of sound which has loaded
  playRingColor: '#000', // amount of sound which has played
  backgroundRingColor: '#eee', // "default" color shown underneath everything else
  animDuration: 500,
  animTransition: Animator.tx.bouncy// http://www.berniecode.com/writing/animator.html
}
</script>